INFO_LEVEL: INFO # DEBUG, INFO, ERROR

use_node: true

type: x-one
init_qpos:
  left_arm: [0, 0, 0, 0, 0, 0]
  left_gripper: 1.0
  right_arm: [0, 0, 0, 0, 0, 0]
  right_gripper: 1.0
control_mode: position
ROBOT_CAN:
  left_arm: can1
  right_arm: can0
CAMERA_SERIALS:
  head: "/dev/video0"
  left_wrist: "/dev/video2"
  right_wrist: "/dev/video4"
bias:
  left_arm:
    gripper: -0.01
  right_arm:
    gripper: -0.01