INFO_LEVEL: INFO # DEBUG, INFO, ERROR

collect:
  task_name: null
  type: x-one-hand
  save_dir: ./data/
  save_format: hdf5
  start_episode: 0
  num_episode: 100
  save_freq: 30  # in Hz
  move_check: true

robot:
  use_node: true

  type: dual_x_arm_hand
  init_qpos: 
    left_arm: [0, 0, 0, 0, 0, 0]
    # left_gripper: 1.0
    left_hand: [[0, 0.0, 0.0, 0.0],  # F1
                [0, 0.0, 0.0, 0.0],  # F2
                [0, 0.0, 0.0, 0.0],  # F3
                [0, 0.0, 0.0, 0.0],  # F4
                [0, 0.0, 0.0, 0.0]]
    right_arm: [0, 0, 0, 0, 0, 0]
    right_hand: [[0, 0.0, 0.0, 0.0],  # F1
                [0, 0.0, 0.0, 0.0],  # F2
                [0, 0.0, 0.0, 0.0],  # F3
                [0, 0.0, 0.0, 0.0],  # F4
                [0, 0.0, 0.0, 0.0]]
    # right_gripper: 1.0
  control_mode: position
  ROBOT_CAN:
    left_arm: can2
    right_arm: can3
  LEFT_HAND_CFG_PATH: "/home/xspark-ai/project/merge/X-One-NT/third_party/wuji_hand/hand_setting.yml"
  RIGHT_HAND_CFG_PATH: "/home/xspark-ai/project/merge/X-One-NT/third_party/wuji_hand/hand_setting.yml"